version: 2
jobs:
  asan:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: ./ci/setup_build_environment.sh
      - run: ./ci/install_bazel.sh
      - run: ./ci/do_ci.sh bazel.asan

  clang_tidy:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: ./ci/setup_build_environment.sh
      - run: ./ci/install_clang.sh
      - run: ./ci/install_bazel.sh
      - run: 
          command: ./ci/do_ci.sh clang_tidy
          no_output_timeout: 1800
      - store_artifacts:
          path: /clang-tidy-result.txt
          destination: /clang-tidy-result.txt
      - store_artifacts:
          path: /clang-tidy-errors.txt
          destination: /clang-tidy-errors.txt

  coverage:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: ./ci/setup_build_environment.sh
      - run: ./ci/install_bazel.sh
      - run: ./ci/do_ci.sh bazel.coverage
      - store_artifacts:
          path: /coverage
          desination: coverage

workflows:
  version: 2
  build_test_and_deploy:
      - asan
        #- coverage
        #- clang_tidy
